# Generated by Django 3.2.9 on 2022-01-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video', models.URLField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='userapp.channel')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='video_dislikes', to='userapp.Channel')),
                ('likes', models.ManyToManyField(blank=True, related_name='video_likes', to='userapp.Channel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='userapp.channel')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to='userapp.Channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='channel.video')),
            ],
        ),
    ]
